### ISSUE TITLE
Delete hpaSepc in seldon deployment doesn't delete the hpa object.

### ISSUE THREAD

**Issue by anggao** [SeldonIO/seldon-operator#69]
We have a seldon deployment, after deleted the hpaSpec from the yaml file, seldon operator didn't remove the hpa object. We are using seldon-operator v0.4.1, wondering is this a bug ?

**Comment by ukclivecox** [comment]
Yes. This may be a valid issue.

**Comment by ukclivecox** [comment]
Can you create the issue on Seldon Core as from 0.5.0 the Operator has been moved to that repo

**Comment by anggao** [comment]
ah sure will do
